name: Latest blog post workflow

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Blog post workflow
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@prabhakarrajput,https://dev.to/feed/prabhakarrajput"
          max_post_count: 5
